### ISSUE TITLE
Accessing txAdmin

### ISSUE THREAD

**Issue by Thomlins** [ich777/docker-fivem-server#6]
I already looked at the preivous issue from January and I've added the variable "+set txAdminPort 40120" and added the port in both TCP and UDP in the template, but I can't seem to get a response from the SERVER-IP:40120. 

Has anything changed since January for this to not work anymore?

**Comment by ich777** [comment]
@Thomlins how did you start the container? Please give me the exact `docker run` comman?
Do you use this container on unRAID?

If you want to run txAdmin you have to leave the variable `GAME_CONFIG` empty, otherwiese it will load the default config where txAdmin is not enabled.

**Comment by Thomlins** [comment]
Thank you for a quick response. I had left the GAME_CONFIG variable with "server.cfg". Removing it did the trick :)

Thanks again!
