### ISSUE TITLE
fxAdmin don't start

### ISSUE THREAD

**Issue by simonzander** [ich777/docker-fivem-server#7]
Hi I follow these topic

https://github.com/ich777/docker-fivem-server/issues/2

but nothing happends. I opened the port and also set these settings

<html><body>

Port configuration | 0.0.0.0:30110  30110/tcp  0.0.0.0:30110  30110/udp  0.0.0.0:30120  30120/tcp  0.0.0.0:30120  30120/udp  0.0.0.0:40121  40121/tcp  0.0.0.0:9016  8080/tcp
-- | --
CMD |  
ENTRYPOINT | /opt/scripts/start.sh
ENV | DATA_DIR                     /serverdata                                        DATA_PERM                     770                                        ENABLE_WEBCONSOLE                     false                                        GAME_CONFIG                     server.cfg                                        GID                     100                                        GOTTY_PARAMS                     -w --title-format FiveM                                        LANG                     en_US.UTF-8                                        LANGUAGE                     en_US:en                                        LC_ALL                     en_US.UTF-8                                        MANUAL_UPDATES                                                             PATH                     /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                        SERVER_DIR                     /serverdata/serverfiles                                        SERVER_KEY                     cfxk_HufFJdSeE77kOQBjASAd_3yM2vl                                        SRV_ADR                     https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/                                        START_VARS                     +set txAdminPort 40121                                        UID                     99                                        UMASK                     000                                        USER                     fivem | DATA_DIR | /serverdata | DATA_PERM | 770 | ENABLE_WEBCONSOLE | false | GAME_CONFIG | server.cfg | GID | 100 | GOTTY_PARAMS | -w --title-format FiveM | LANG | en_US.UTF-8 | LANGUAGE | en_US:en | LC_ALL | en_US.UTF-8 | MANUAL_UPDATES |   | PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin | SERVER_DIR | /serverdata/serverfiles | SERVER_KEY | cfxk_HufFJdSeE77kOQBjASAd_3yM2vl | SRV_ADR | https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/ | START_VARS | +set txAdminPort 40121 | UID | 99 | UMASK | 000 | USER | fivem
DATA_DIR | /serverdata
DATA_PERM | 770
ENABLE_WEBCONSOLE | false
GAME_CONFIG | server.cfg
GID | 100
GOTTY_PARAMS | -w --title-format FiveM
LANG | en_US.UTF-8
LANGUAGE | en_US:en
LC_ALL | en_US.UTF-8
MANUAL_UPDATES |  
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVER_DIR | /serverdata/serverfiles
SRV_ADR | https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/
START_VARS | +set txAdminPort 40121
UID | 99
UMASK | 000
USER | fivem

</body>
</html>

**Comment by ich777** [comment]
Hi,
leave the variable `GAME_CONFIG` empty then fxAdmin will start, if the variable is not empty fxAdmin will not start.

Hope this helps. Let me know if you need anything else.

**Comment by ich777** [comment]
@sbergt do you use this container on Unraid or another system? Is this resolved now?

**Comment by simonzander** [comment]
Thanks It worked for me. I use portainer to manage my containers
