### ISSUE TITLE
Unable to run Txadmin unless started manualy via terminal

### ISSUE THREAD

**Issue by luxu-gg** [ich777/docker-fivem-server#8]
Hello, I am using this on my unraid setup. However even after creating the port as instructed and adding the necessary start options. My txadmin simply does not run.
The only way I was able to make it run, was to navigate to the directory via unraid's terminal and then running: `./run.sh +set txAdminPort 40120 +set onesync on +set serverProfile dev_server`
When I simply use unraid to start this container, it skips txadmin.

<img width="1367" alt="image" src="https://github.com/ich777/docker-fivem-server/assets/122475744/c0c5b2dd-41bc-47e9-8c01-c2a0b1b86743">
<img width="1302" alt="image" src="https://github.com/ich777/docker-fivem-server/assets/122475744/58cc9568-d3d8-4c75-9c83-c3124ca9e35f">

Console: 
<img width="1160" alt="image" src="https://github.com/ich777/docker-fivem-server/assets/122475744/f547cb8e-2d32-4fa4-b744-89ebd4694c06">

**Comment by luxu-gg** [comment]
<img width="1286" alt="image" src="https://github.com/ich777/docker-fivem-server/assets/122475744/000763e2-c4dc-4497-b95d-bb74b61a8fd8">

Leaving this empty seems to fix the issue

**Comment by ich777** [comment]
Exactly, like it is mentioned in the description from the variable.
